feature: adds snippets
dfinity/vscode-motoko pull request #18
Opened 2021-08-12 18:53 UTC by krpeacock

2021-08-12 21:44 UTC, crusso reviewed
Thanks for starting on this. Some minor comments

2021-08-12 21:44 UTC, crusso commented on snippets.json
> +            "var ${1:i} = 0;",
This one looks a bit too specialized, why declare both i and j and increment i by j?
```
for (... in Iter.range(...,...)) {
  ...
};
```
or even just
```
for (... in ...) {
  ...
};
```
might be all you want in this.

(The former won't be well-typed unless Iter is imported...)

2021-08-12 21:44 UTC, crusso commented on snippets.json
> +        "description": "a variable type block"
```suggestion
        "description": "a variant type block"
```

2021-08-14 19:46 UTC, o0x requested changes

2021-08-14 19:46 UTC, o0x commented on snippets.json
> +}
```suggestion
    "Switch Statement": {
        "prefix": [
            "switch"
        ],
        "body": [
            "switch($1) {",
            "\tcase($2) {$0};",
            "\tcase($3) { };",
            "};"
        ]
    },
}
```

2021-08-18 18:39 UTC, ikincihallac approved these changes

2022-12-01 00:09 UTC, rvanasa commented
Merging in #106. 

@krpeacock, let me know if you have any suggestions from your work on this original PR.

2022-12-01 00:10 UTC, closed without merging